"""empty message

Revision ID: 8ac26dbe70a1
Revises: ca7ae9ea86b5
Create Date: 2024-07-16 09:58:40.509967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ac26dbe70a1'
down_revision = 'ca7ae9ea86b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=250), nullable=False),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('crew', sa.Integer(), nullable=True),
    sa.Column('vehicle_class', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicles')
    # ### end Alembic commands ###
